spring.application.name=billing-service
server.port=8083

spring.datasource.url=jdbc:h2:mem:billing-db
spring.h2.console.enabled=true

spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}


# Default page number if not specified (usually 0)
spring.data.web.pageable.page-parameter=page
# Default page size if not specified (Spring default is 20)
spring.data.web.pageable.default-page-size=10
# Maximum page size a client is allowed to request (prevents memory issues)
spring.data.web.pageable.max-page-size=50